move exp-asynccache to be a peer dependency
BonnierNews/exp-fetch pull request #35
Opened 2021-12-09 13:50 UTC by andolf

2022-04-29 06:55 UTC, paed01 requested changes
I like it. We could also consider dropping the package-lock all-together, lots of bytes.

2022-04-29 07:23 UTC, markusn reviewed
Why is this change needed?

2022-04-29 07:43 UTC, andolf commented
It's a long time since I did this PR so this is as far as I can remember.
The biggest problem was when I updated `exp-asynccache` and tried to upgrade that package in existing projects: if the project in question used `exp-fetch` then there would exist multiple versions of `exp-asynccache` and at some times it had weird side-effects such as not knowing what API was actually in use. Specifying it as a peer dependency would alleviate some of those problems.

2022-04-29 07:57 UTC, markusn requested changes

2022-04-29 07:57 UTC, markusn commented on .github/workflows/build-latest.yaml
> +      - run: npm install
I really don't see the point of this. Dropping the package-lock.json and the usage om npm ci means that the "build" will no longer be reproducible

2022-04-29 09:03 UTC, andolf commented
I'm a little bit torn on the implementation:
`exp-fetch` includes a cache by default, which constitutes a requirement to install `exp-asynccache`. However, you can set `cache: null`, but that _still_ requires you to install the cache lib.

2022-09-12 12:12 UTC, andolf commented
Closing this because of lack of inactivity

2022-09-12 12:12 UTC, closed without merging